// navigation
export const NAVIGATION_GOTO_LOGIN = 'Navigation/GOTO_LOGIN';
export const NAVIGATION_GOTO_MAIN = 'Navigation/GOTO_MAIN';
// authentication
export const AUTH_LOGIN_USER_REQUEST = 'AUTH_LOGIN_USER_REQUEST';
export const AUTH_LOGIN_USER_SUCCESS = 'AUTH_LOGIN_USER_SUCCESS';
export const AUTH_LOGIN_USER_FAILURE = 'AUTH_LOGIN_USER_FAILURE';
export const AUTH_LOGIN_USER_EXPIRED = 'AUTH_LOGIN_USER_EXPIRED';
